# resource
# https://www.padok.fr/en/blog/codepipeline-eks-helm

version: 0.2

env:
  variables:
    PROJECT_NAME: "rdtf"
    #TODO: add list of users
    USERS: "arn:aws:iam::146452989591:user/Han.Tu"
    # run AWS.exe by 
    # & $env:AWSCLI
    AWSCLI: 'C:\Program Files\Amazon\AWSCLI\bin\aws.exe'
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes

phases:
  install: # Install Chocolatey, AWS CLI, Terraform, Kubectl
    commands:
      # Chocolatey 
      - "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      # AWS CLI, Terraform, Kubectl
      - choco install -yvf terraform kubernetes-cli
      - choco upgrade -yvf awscli --version 1.18.6 # AWS build server contains 1.14.x, which predates EKS, and this choco installs breaks with AWSCLI 2+, so we're stuck with one of the last 1.x
  pre_build:
    commands:
  build:
    commands:
      #! TODO - confirm usage 
      
      # app 
      - set-location app
      # run TF for Destroy app
      - .\app_setup.ps1 $PROJECT_NAME $env:AWS_REGION
      - terraform init -input=false
      - terraform destroy -auto-approve

      # EKS
      - set-location ..\eks\terraform
      # run TF for EKS
      - .\terraform_setup.ps1 $PROJECT_NAME $env:AWS_REGION
      - terraform init -input=false
      - terraform destroy -auto-approve

      # Remote backend
      - set-location ..\remote-backend
      #run TF for backend
      - .\backend_setup.ps1 $PROJECT_NAME $env:AWS_REGION
      - terraform init -input=false
      - terraform destroy -auto-approve
      

  #post_build:
    #commands: 
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths